# Generated by Django 4.2.9 on 2024-05-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                null=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="auth.group",
            ),
        )
    ]
