# Generated by Django 5.0.6 on 2024-05-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calendar', '0002_rename_calender_id_event_calender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calender',
            new_name='calendar',
        ),
    ]
