# Generated by Django 4.2.11 on 2024-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_schedule_delete_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="Day",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="Hours",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="Stage",
            field=models.IntegerField(),
        ),
    ]
