# Generated by Django 4.2.11 on 2024-05-04 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_alter_schedule_day_alter_schedule_hours_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schedule",
            new_name="Artist",
        ),
    ]
