# Generated by Django 4.2.11 on 2024-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_rename_schedule_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="Stage",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="artist",
            name="country",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="artist",
            name="genre",
            field=models.CharField(max_length=40),
        ),
    ]
