# Generated by Django 4.2.11 on 2024-05-07 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_alter_artist_stage_alter_artist_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="Day",
            new_name="day",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="Hours",
            new_name="hours",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="Stage",
            new_name="stage",
        ),
    ]
