# Generated by Django 4.2.11 on 2024-05-12 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_bulletinboardmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinboardmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
