# Generated by Django 4.2.11 on 2024-05-13 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_alter_bulletinboardmessage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('stage', models.PositiveIntegerField()),
                ('hours', models.IntegerField()),
                ('genre', models.CharField(choices=[('BCHT', 'Bachata'), ('BND', 'Banda'), ('HS', 'House'), ('TRNC', 'Electronic'), ('FNK', 'Funk'), ('HHP', 'HipHop'), ('RGG', 'Reggea'), ('RGGT', 'Reggeaton'), ('MTL', 'Metal'), ('PNK', 'Punk'), ('RP', 'Rap'), ('RCK', 'Rock'), ('TRC', 'Trance'), ('TECH', 'Techno')], max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='user',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='role',
        ),
        migrations.AddField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group'),
        ),
    ]
