# Generated by Django 4.2.11 on 2024-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_shoppingchecklist_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
    ]
