# Generated by Django 4.2.9 on 2024-05-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shopping_checklist", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="bought",
            field=models.BooleanField(default=False),
        )
    ]
