# Generated by Django 4.2.11 on 2024-05-17 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('shopping_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingchecklist',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='shoppingchecklist',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.event'),
        ),
        migrations.AddField(
            model_name='shoppingchecklist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppingchecklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
