# Generated by Django 4.2.11 on 2024-05-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_checklist', '0002_remove_shoppingchecklist_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingchecklist',
            name='date_created',
        ),
    ]
