# Generated by Django 4.2.9 on 2024-05-03 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("shopping_checklist", "0002_shoppingitem_bought")]

    operations = [
        migrations.RemoveField(model_name="shoppingchecklist", name="date_created"),
        migrations.AddField(
            model_name="shoppingchecklist",
            name="date_time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
