# Generated by Django 4.2.11 on 2024-05-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_artist_rename_user_groupmembership_member_and_more'),
        ('shopping_checklist', '0002_remove_shoppingchecklist_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingchecklist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.group'),
        ),
    ]
