# Generated by Django 4.2.11 on 2024-05-14 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_shoppingchecklist_shoppingitem'),
        ('shopping_checklist', '0003_alter_shoppingchecklist_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingchecklist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_checklists_from_shopping', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='shoppingchecklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_checklists_from_shopping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_checklist.shoppingchecklist'),
        ),
    ]
