# Generated by Django 4.2.9 on 2024-05-05 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopping_checklist", "0003_remove_shoppingchecklist_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingchecklist",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
