# Generated by Django 4.2.9 on 2024-05-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_admin_user_alter_event_group"),
        ("shopping_checklist", "0004_shoppingchecklist_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingchecklist",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="events.event",
            ),
        )
    ]
