# Generated by Django 4.2.9 on 2024-05-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shopping_checklist", "0005_shoppingchecklist_event")]

    operations = [
        migrations.RemoveField(model_name="shoppingchecklist", name="assigned_to")
    ]
