# Generated by Django 4.2.9 on 2024-05-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shopping_checklist", "0006_remove_shoppingchecklist_assigned_to")]

    operations = [
        migrations.AddField(
            model_name="shoppingchecklist",
            name="name",
            field=models.CharField(default="Lidl", max_length=100),
            preserve_default=False,
        )
    ]
